from django.db import models
from django.utils import timezone


class TradingSignal(models.Model):
    """Model to store trading signals generated by the system"""

    SIGNAL_TYPES = [
        ('BUY', 'Buy'),
        ('SELL', 'Sell'),
    ]

    STRATEGY_TYPES = [
        ('ORB', 'Opening Range Breakout'),
        ('VWAP_PULLBACK', 'VWAP Pullback'),
        ('CONFLUENCE_REVERSAL', 'Confluence Reversal'),
    ]

    # Basic Signal Info
    symbol = models.CharField(max_length=20, db_index=True)
    signal_type = models.CharField(max_length=4, choices=SIGNAL_TYPES, db_index=True)
    strategy = models.CharField(max_length=30, choices=STRATEGY_TYPES, db_index=True)
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)

    # Price Levels
    entry_price = models.DecimalField(max_digits=10, decimal_places=2)
    stop_loss = models.DecimalField(max_digits=10, decimal_places=2)
    target_price = models.DecimalField(max_digits=10, decimal_places=2)
    current_price = models.DecimalField(max_digits=10, decimal_places=2)

    # Risk Management
    risk_amount = models.DecimalField(max_digits=12, decimal_places=2)
    reward_amount = models.DecimalField(max_digits=12, decimal_places=2)
    rrr = models.DecimalField(max_digits=5, decimal_places=2, help_text="Risk-Reward Ratio")
    position_size = models.IntegerField(help_text="Number of shares")
    capital_required = models.DecimalField(max_digits=12, decimal_places=2)
    max_risk = models.DecimalField(max_digits=12, decimal_places=2)

    # Technical Indicators
    rsi = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    vwap = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    atr = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    macd = models.DecimalField(max_digits=10, decimal_places=4, null=True, blank=True)
    macd_signal = models.DecimalField(max_digits=10, decimal_places=4, null=True, blank=True)
    macd_histogram = models.DecimalField(max_digits=10, decimal_places=4, null=True, blank=True)
    ema_short = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    ema_long = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    volume = models.BigIntegerField(null=True, blank=True)
    avg_volume_20 = models.BigIntegerField(null=True, blank=True)
    volume_ratio = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    # Support/Resistance
    support_level = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    resistance_level = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    # ORB Levels
    orb_high = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    orb_low = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    orb_midpoint = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    # Bollinger Bands
    bb_upper = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    bb_middle = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    bb_lower = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    # Additional Metrics
    confidence_score = models.DecimalField(max_digits=5, decimal_places=2, db_index=True)
    confluences = models.TextField(help_text="Comma-separated list of confluence factors")

    # Status Tracking
    is_active = models.BooleanField(default=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-confidence_score', '-timestamp']
        indexes = [
            models.Index(fields=['-timestamp', 'signal_type']),
            models.Index(fields=['symbol', '-timestamp']),
            models.Index(fields=['-confidence_score']),
        ]

    def __str__(self):
        return f"{self.symbol} - {self.signal_type} ({self.strategy}) @ ₹{self.entry_price}"

    @property
    def confluences_list(self):
        """Return confluences as a list"""
        if self.confluences:
            return [c.strip() for c in self.confluences.split(',')]
        return []

    @property
    def potential_profit(self):
        """Calculate potential profit percentage"""
        if self.signal_type == 'BUY':
            return ((self.target_price - self.entry_price) / self.entry_price) * 100
        else:
            return ((self.entry_price - self.target_price) / self.entry_price) * 100

    @property
    def potential_loss(self):
        """Calculate potential loss percentage"""
        if self.signal_type == 'BUY':
            return ((self.entry_price - self.stop_loss) / self.entry_price) * 100
        else:
            return ((self.stop_loss - self.entry_price) / self.entry_price) * 100


class MarketData(models.Model):
    """Model to store market-wide data like NIFTY PCR"""

    timestamp = models.DateTimeField(default=timezone.now, db_index=True)

    # Market Indices
    nifty_50 = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    nifty_bank = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    # Market Breadth
    pcr_ratio = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True,
                                    help_text="Put-Call Ratio")
    advance_decline = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    # Volatility
    india_vix = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    # Sentiment
    market_sentiment = models.CharField(max_length=20, choices=[
        ('BULLISH', 'Bullish'),
        ('BEARISH', 'Bearish'),
        ('NEUTRAL', 'Neutral'),
    ], default='NEUTRAL')

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']
        verbose_name_plural = "Market Data"

    def __str__(self):
        return f"Market Data - {self.timestamp.strftime('%Y-%m-%d %H:%M')}"


class ScanSession(models.Model):
    """Track each scanning session"""

    timestamp = models.DateTimeField(default=timezone.now, db_index=True)
    total_signals = models.IntegerField(default=0)
    buy_signals = models.IntegerField(default=0)
    sell_signals = models.IntegerField(default=0)
    total_capital_required = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_potential_profit = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    scan_duration = models.DurationField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=[
        ('RUNNING', 'Running'),
        ('COMPLETED', 'Completed'),
        ('FAILED', 'Failed'),
    ], default='RUNNING')

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"Scan Session - {self.timestamp.strftime('%Y-%m-%d %H:%M')} ({self.total_signals} signals)"


class NewsItem(models.Model):
    """Store news items for stocks"""

    symbol = models.CharField(max_length=20, db_index=True)
    title = models.CharField(max_length=500)
    url = models.URLField(max_length=1000, blank=True)
    published_at = models.DateTimeField(db_index=True)
    source = models.CharField(max_length=100)

    # Sentiment Analysis
    sentiment = models.CharField(max_length=20, choices=[
        ('POSITIVE', 'Positive'),
        ('NEGATIVE', 'Negative'),
        ('NEUTRAL', 'Neutral'),
    ], db_index=True)
    sentiment_score = models.DecimalField(max_digits=5, decimal_places=2,
                                         help_text="Sentiment score from -2.0 to +2.0")

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-published_at']
        indexes = [
            models.Index(fields=['symbol', '-published_at']),
        ]

    def __str__(self):
        return f"{self.symbol} - {self.title[:50]}..."
