# Generated by Django 5.2.8 on 2025-11-16 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "nifty_50",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "nifty_bank",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pcr_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Put-Call Ratio",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "advance_decline",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "india_vix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "market_sentiment",
                    models.CharField(
                        choices=[
                            ("BULLISH", "Bullish"),
                            ("BEARISH", "Bearish"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Market Data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("total_signals", models.IntegerField(default=0)),
                ("buy_signals", models.IntegerField(default=0)),
                ("sell_signals", models.IntegerField(default=0)),
                (
                    "total_capital_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_potential_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("scan_duration", models.DurationField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("source", models.CharField(max_length=100)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEGATIVE", "Negative"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sentiment score from -2.0 to +2.0",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-published_at"],
                        name="signals_new_symbol_db2e2e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TradingSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        db_index=True,
                        max_length=4,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("ORB", "Opening Range Breakout"),
                            ("VWAP_PULLBACK", "VWAP Pullback"),
                            ("CONFLUENCE_REVERSAL", "Confluence Reversal"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("risk_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reward_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "rrr",
                    models.DecimalField(
                        decimal_places=2, help_text="Risk-Reward Ratio", max_digits=5
                    ),
                ),
                ("position_size", models.IntegerField(help_text="Number of shares")),
                (
                    "capital_required",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("max_risk", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "rsi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "vwap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "atr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "macd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "macd_signal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "macd_histogram",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "ema_short",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ema_long",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("avg_volume_20", models.BigIntegerField(blank=True, null=True)),
                (
                    "volume_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "support_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "resistance_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "orb_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "orb_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "orb_midpoint",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bb_upper",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bb_middle",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bb_lower",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
                ),
                (
                    "confluences",
                    models.TextField(
                        help_text="Comma-separated list of confluence factors"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-confidence_score", "-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "signal_type"],
                        name="signals_tra_timesta_d150ea_idx",
                    ),
                    models.Index(
                        fields=["symbol", "-timestamp"],
                        name="signals_tra_symbol_69ca6d_idx",
                    ),
                    models.Index(
                        fields=["-confidence_score"],
                        name="signals_tra_confide_9f5f4a_idx",
                    ),
                ],
            },
        ),
    ]
